
#ifndef _IOCTL_H
#define _IOCTL_H

#pragma once

// abort
// 22C004
#define TPM_CANCEL_COMMAND  \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x1,METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

// Transmit
// 22C00C
#define TPM_TRANSMIT_COMMAND  \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x3,METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

// TPM_SUMBIT_ACPI_COMMAND
// 22C014
#define TPM_SUMBIT_ACPI_COMMAND \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x5,METHOD_BUFFERED,FILE_READ_DATA | FILE_WRITE_DATA)

#endif // _IOCTL_H
